import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { app } from "@/utils/firebase/firebase";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/*
https://console.firebase.google.com/u/0/project/task-manager-7192b/authentication/users
https://firebase.google.com/docs/hosting/frameworks/nextjs
https://firebase.google.com/docs/cli#mac-linux-npm
https://firebase.google.com/codelabs/firebase-nextjs#5
https://github.com/firebase/friendlyeats-web/blob/master/nextjs-start/src/app/layout.js
*/

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  console.log(app);
  return (
    <html lang="en">
      <body className={`${inter.className} min-h-screen`}>{children}</body>
    </html>
  );
}
